apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-metric-servicemonitor
  labels:
    app: prometheus
  namespace: kfserving-monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: "prometheus-custom-exporter"
  endpoints:
  - port: metrics
    path: '/metrics'
    interval: 5s